# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: food.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'food.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfood.proto\x12\x07pb.food\x1a\x0c\x63ommon.proto\"`\n\x12GetAllFoodsRequest\x12\x1a\n\x08\x62ranchID\x18\x01 \x01(\x03R\x08\x62ranchID\x12\x12\n\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n\x08pageSize\x18\x03 \x01(\x05R\x08pageSize\"\x98\x01\n\x04\x46ood\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12\x12\n\x04type\x18\x04 \x01(\tR\x04type\x12 \n\x0bisAvailable\x18\x05 \x01(\x08R\x0bisAvailable\x12\x14\n\x05price\x18\x06 \x01(\x01R\x05price\"\xd8\x01\n\x13GetAllFoodsResponse\x12#\n\x05\x66oods\x18\x01 \x03(\x0b\x32\r.pb.food.FoodR\x05\x66oods\x12=\n\x0epaginationInfo\x18\x02 \x01(\x0b\x32\x15.pb.common.PaginationR\x0epaginationInfo\x12\x38\n\x05\x65xtra\x18\x03 \x01(\x0b\x32\".pb.food.GetAllFoodsResponse.ExtraR\x05\x65xtra\x1a#\n\x05\x45xtra\x12\x1a\n\x08\x62ranchID\x18\x02 \x01(\x03R\x08\x62ranchID\"\x8f\x01\n\x11\x43reateFoodRequest\x12\x1a\n\x08\x62ranchID\x18\x01 \x01(\x03R\x08\x62ranchID\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12\x12\n\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n\x05price\x18\x06 \x01(\x01R\x05price2V\n\x08\x41llFoods\x12J\n\x0bGetAllFoods\x12\x1b.pb.food.GetAllFoodsRequest\x1a\x1c.pb.food.GetAllFoodsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'food_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETALLFOODSREQUEST']._serialized_start=37
  _globals['_GETALLFOODSREQUEST']._serialized_end=133
  _globals['_FOOD']._serialized_start=136
  _globals['_FOOD']._serialized_end=288
  _globals['_GETALLFOODSRESPONSE']._serialized_start=291
  _globals['_GETALLFOODSRESPONSE']._serialized_end=507
  _globals['_GETALLFOODSRESPONSE_EXTRA']._serialized_start=472
  _globals['_GETALLFOODSRESPONSE_EXTRA']._serialized_end=507
  _globals['_CREATEFOODREQUEST']._serialized_start=510
  _globals['_CREATEFOODREQUEST']._serialized_end=653
  _globals['_ALLFOODS']._serialized_start=655
  _globals['_ALLFOODS']._serialized_end=741
# @@protoc_insertion_point(module_scope)
