// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tools.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QrCodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	BackgroundColor *QrCodeRequest_Color   `protobuf:"bytes,2,opt,name=backgroundColor,proto3" json:"backgroundColor,omitempty"`
	ForegroundColor *QrCodeRequest_Color   `protobuf:"bytes,3,opt,name=foregroundColor,proto3" json:"foregroundColor,omitempty"`
	HasBorder       bool                   `protobuf:"varint,4,opt,name=hasBorder,proto3" json:"hasBorder,omitempty"`
	Size            int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QrCodeRequest) Reset() {
	*x = QrCodeRequest{}
	mi := &file_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrCodeRequest) ProtoMessage() {}

func (x *QrCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrCodeRequest.ProtoReflect.Descriptor instead.
func (*QrCodeRequest) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{0}
}

func (x *QrCodeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *QrCodeRequest) GetBackgroundColor() *QrCodeRequest_Color {
	if x != nil {
		return x.BackgroundColor
	}
	return nil
}

func (x *QrCodeRequest) GetForegroundColor() *QrCodeRequest_Color {
	if x != nil {
		return x.ForegroundColor
	}
	return nil
}

func (x *QrCodeRequest) GetHasBorder() bool {
	if x != nil {
		return x.HasBorder
	}
	return false
}

func (x *QrCodeRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type QrCodeRequest_Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             uint64                 `protobuf:"varint,1,opt,name=R,proto3" json:"R,omitempty"`
	G             uint64                 `protobuf:"varint,2,opt,name=G,proto3" json:"G,omitempty"`
	B             uint64                 `protobuf:"varint,3,opt,name=B,proto3" json:"B,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrCodeRequest_Color) Reset() {
	*x = QrCodeRequest_Color{}
	mi := &file_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrCodeRequest_Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrCodeRequest_Color) ProtoMessage() {}

func (x *QrCodeRequest_Color) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrCodeRequest_Color.ProtoReflect.Descriptor instead.
func (*QrCodeRequest_Color) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{0, 0}
}

func (x *QrCodeRequest_Color) GetR() uint64 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *QrCodeRequest_Color) GetG() uint64 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *QrCodeRequest_Color) GetB() uint64 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_tools_proto protoreflect.FileDescriptor

const file_tools_proto_rawDesc = "" +
	"\n" +
	"\vtools.proto\"\x86\x02\n" +
	"\rQrCodeRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12>\n" +
	"\x0fbackgroundColor\x18\x02 \x01(\v2\x14.QrCodeRequest.ColorR\x0fbackgroundColor\x12>\n" +
	"\x0fforegroundColor\x18\x03 \x01(\v2\x14.QrCodeRequest.ColorR\x0fforegroundColor\x12\x1c\n" +
	"\thasBorder\x18\x04 \x01(\bR\thasBorder\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\x1a1\n" +
	"\x05Color\x12\f\n" +
	"\x01R\x18\x01 \x01(\x04R\x01R\x12\f\n" +
	"\x01G\x18\x02 \x01(\x04R\x01G\x12\f\n" +
	"\x01B\x18\x03 \x01(\x04R\x01BB/Z-github.com/KhoshMaze/khoshmaze-backend/api/pbb\x06proto3"

var (
	file_tools_proto_rawDescOnce sync.Once
	file_tools_proto_rawDescData []byte
)

func file_tools_proto_rawDescGZIP() []byte {
	file_tools_proto_rawDescOnce.Do(func() {
		file_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)))
	})
	return file_tools_proto_rawDescData
}

var file_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tools_proto_goTypes = []any{
	(*QrCodeRequest)(nil),       // 0: QrCodeRequest
	(*QrCodeRequest_Color)(nil), // 1: QrCodeRequest.Color
}
var file_tools_proto_depIdxs = []int32{
	1, // 0: QrCodeRequest.backgroundColor:type_name -> QrCodeRequest.Color
	1, // 1: QrCodeRequest.foregroundColor:type_name -> QrCodeRequest.Color
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tools_proto_init() }
func file_tools_proto_init() {
	if File_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tools_proto_goTypes,
		DependencyIndexes: file_tools_proto_depIdxs,
		MessageInfos:      file_tools_proto_msgTypes,
	}.Build()
	File_tools_proto = out.File
	file_tools_proto_goTypes = nil
	file_tools_proto_depIdxs = nil
}
