// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: tools.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QrCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url             string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	BackgroundColor *QrCodeRequest_Color `protobuf:"bytes,2,opt,name=backgroundColor,proto3" json:"backgroundColor,omitempty"`
	ForegroundColor *QrCodeRequest_Color `protobuf:"bytes,3,opt,name=foregroundColor,proto3" json:"foregroundColor,omitempty"`
	HasBorder       bool                 `protobuf:"varint,4,opt,name=hasBorder,proto3" json:"hasBorder,omitempty"`
	Size            int32                `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *QrCodeRequest) Reset() {
	*x = QrCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QrCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrCodeRequest) ProtoMessage() {}

func (x *QrCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrCodeRequest.ProtoReflect.Descriptor instead.
func (*QrCodeRequest) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{0}
}

func (x *QrCodeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *QrCodeRequest) GetBackgroundColor() *QrCodeRequest_Color {
	if x != nil {
		return x.BackgroundColor
	}
	return nil
}

func (x *QrCodeRequest) GetForegroundColor() *QrCodeRequest_Color {
	if x != nil {
		return x.ForegroundColor
	}
	return nil
}

func (x *QrCodeRequest) GetHasBorder() bool {
	if x != nil {
		return x.HasBorder
	}
	return false
}

func (x *QrCodeRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type QrCodeRequest_Color struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R uint64 `protobuf:"varint,1,opt,name=R,proto3" json:"R,omitempty"`
	G uint64 `protobuf:"varint,2,opt,name=G,proto3" json:"G,omitempty"`
	B uint64 `protobuf:"varint,3,opt,name=B,proto3" json:"B,omitempty"`
}

func (x *QrCodeRequest_Color) Reset() {
	*x = QrCodeRequest_Color{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QrCodeRequest_Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrCodeRequest_Color) ProtoMessage() {}

func (x *QrCodeRequest_Color) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrCodeRequest_Color.ProtoReflect.Descriptor instead.
func (*QrCodeRequest_Color) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{0, 0}
}

func (x *QrCodeRequest_Color) GetR() uint64 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *QrCodeRequest_Color) GetG() uint64 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *QrCodeRequest_Color) GetB() uint64 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_tools_proto protoreflect.FileDescriptor

var file_tools_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x02,
	0x0a, 0x0d, 0x51, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x3e, 0x0a, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x51, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x52, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x3e, 0x0a, 0x0f, 0x66, 0x6f, 0x72, 0x65, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x51, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x52, 0x0f, 0x66, 0x6f, 0x72, 0x65, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61, 0x73, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x1a, 0x31, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01,
	0x52, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x52, 0x12, 0x0c, 0x0a, 0x01, 0x47, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x47, 0x12, 0x0c, 0x0a, 0x01, 0x42, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x01, 0x42, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x68, 0x6f, 0x73, 0x68, 0x4d, 0x61, 0x7a, 0x65, 0x2f, 0x6b,
	0x68, 0x6f, 0x73, 0x68, 0x6d, 0x61, 0x7a, 0x65, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tools_proto_rawDescOnce sync.Once
	file_tools_proto_rawDescData = file_tools_proto_rawDesc
)

func file_tools_proto_rawDescGZIP() []byte {
	file_tools_proto_rawDescOnce.Do(func() {
		file_tools_proto_rawDescData = protoimpl.X.CompressGZIP(file_tools_proto_rawDescData)
	})
	return file_tools_proto_rawDescData
}

var file_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tools_proto_goTypes = []interface{}{
	(*QrCodeRequest)(nil),       // 0: QrCodeRequest
	(*QrCodeRequest_Color)(nil), // 1: QrCodeRequest.Color
}
var file_tools_proto_depIdxs = []int32{
	1, // 0: QrCodeRequest.backgroundColor:type_name -> QrCodeRequest.Color
	1, // 1: QrCodeRequest.foregroundColor:type_name -> QrCodeRequest.Color
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tools_proto_init() }
func file_tools_proto_init() {
	if File_tools_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tools_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QrCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QrCodeRequest_Color); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tools_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tools_proto_goTypes,
		DependencyIndexes: file_tools_proto_depIdxs,
		MessageInfos:      file_tools_proto_msgTypes,
	}.Build()
	File_tools_proto = out.File
	file_tools_proto_rawDesc = nil
	file_tools_proto_goTypes = nil
	file_tools_proto_depIdxs = nil
}
